apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-test-annotations
spec:
  selector:
    matchLabels:
      app: metrics-test-annotations
  replicas: 1
  template:
    metadata:
      name: metrics-test-annotations
      labels:
        app: metrics-test-annotations
    spec:
      containers:
        - name: metrics
          image: registry.cn-shenzhen.aliyuncs.com/pdf/metrics:v2
          ports:
            - containerPort: 8080
