apiVersion: v1
kind: Service
metadata:
  name: metrics-test-annotations-svc
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8080"
    prometheus.io/path: "/swagger-stats/metrics"
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: metrics-test-annotations