apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: caizhi-svc
  name: caizhi-demo
  namespace: monitoring
spec:
  # 不要用 any: true 要用matchNames
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - interval: 3s
      port: metrics
      path: /swagger-stats/metrics
  selector:
    matchLabels:
      external: caizhi
---
kind: Service
apiVersion: v1
metadata:
  name: caizhi-svc
#  annotations:
#    prometheus.io/scrape: "true"
#    prometheus.io/port: "7001"
#    prometheus.io/path: "/swagger-stats/metrics"
  labels:
    external: caizhi
spec:
  type: ExternalName
  ports:
    - port: 80
      name: metrics
  externalName: metrics.ngrok.pengdafu.ren