apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: default
  name: ci-test
spec:
  selector:
    matchLabels:
      app: ci-test
  replicas: 3
  template:
    metadata:
      name: ci-test
      namespace: default
      labels:
        app: ci-test
    spec:
      containers:
        - name: ci-test
          image: reg.pdf.cn/ci/myapp:v2
          ports:
            - containerPort: 8080
              name: http
      imagePullSecrets:
        - name: harbor
---
apiVersion: v1
kind: Service
metadata:
  name: ci-test-svc
  namespace: default
spec:
  ports:
    - port: 8080
      name: http
  selector:
    app: ci-test

---
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ci-test-is
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
    - http:
        paths:
          - backend:
              serviceName: ci-test-svc
              servicePort: http
      host: test.local.ci