apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    k8s-app: demo
  name: demo
  namespace: monitoring
spec:
  # 不要用 any: true 要用matchNames
  namespaceSelector:
    matchNames:
      - default
  endpoints:
    - interval: 3s
      port: metrics
      path: /metrics
  selector:
    matchLabels:
      app: metrics-svc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: metrics-svc
  name: metrics-svc
spec:
  ports:
    - port: 8080
      name: metrics
  selector:
    app: metrics-test